services:
  source:
    image: mysql:8.0.30
    container_name: source
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: oms2
      MYSQL_USER: replica
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin
    volumes:
      - ./source_data:/var/lib/mysql
    networks:
      - oms2-network
      
  replica:
    image: mysql:8.0.30
    container_name: replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: oms2
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password --server-id=2 --relay-log=mysql-relay-bin
    volumes:
      - ./replica_data:/var/lib/mysql
    networks: 
      - oms2-network
    depends_on:
      - source
      
networks:
  oms2-network:
    name: oms2-network   
    driver: bridge
      

